Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/supplychain.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.supplychain.com:7050
      - orderer2.supplychain.com:8050
      - orderer3.supplychain.com:9050

  - &farmer
      Name: farmerMSP
      ID: farmerMSP
      MSPDir: ../organizations/peerOrganizations/farmer.supplychain.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('farmerMSP.admin', 'farmerMSP.peer', 'farmerMSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('farmerMSP.admin', 'farmerMSP.peer', 'farmerMSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('farmerMSP.admin', 'farmerMSP.peer', 'farmerMSP.client')"
        Endorsement:
          Type: Signature
          Rule: "OR('farmerMSP.admin', 'farmerMSP.peer', 'farmerMSP.client')"
      AnchorPeers:
        - Host: peer0.farmer.supplychain.com
          Port: 7051

  - &warehouse
      Name: warehouseMSP
      ID: warehouseMSP
      MSPDir: ../organizations/peerOrganizations/warehouse.supplychain.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('warehouseMSP.admin', 'warehouseMSP.peer', 'warehouseMSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('warehouseMSP.admin', 'warehouseMSP.peer', 'warehouseMSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('warehouseMSP.admin', 'warehouseMSP.peer', 'warehouseMSP.client')"
        Endorsement:
          Type: Signature
          Rule: "OR('warehouseMSP.admin', 'warehouseMSP.peer', 'warehouseMSP.client')"
      AnchorPeers:
        - Host: peer0.warehouse.supplychain.com
          Port: 9051

  - &retailer
      Name: retailerMSP
      ID: retailerMSP
      MSPDir: ../organizations/peerOrganizations/retailer.supplychain.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
        Endorsement:
          Type: Signature
          Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
      AnchorPeers:
        - Host: peer0.retailer.supplychain.com
          Port: 11051

  - &transporter
      Name: transporterMSP
      ID: transporterMSP
      MSPDir: ../organizations/peerOrganizations/transporter.supplychain.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
        Endorsement:
          Type: Signature
          Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
      AnchorPeers:
        - Host: peer0.transporter.supplychain.com
          Port: 13051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.supplychain.com:7050
    - orderer2.supplychain.com:8050
    - orderer3.supplychain.com:9050
  EtcdRaft:
    Consenters:
    - Host: orderer.supplychain.com
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer.supplychain.com/tls/server.crt
    - Host: orderer2.supplychain.com
      Port: 8050
      ClientTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer2.supplychain.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer2.supplychain.com/tls/server.crt
    - Host: orderer3.supplychain.com
      Port: 9050
      ClientTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer3.supplychain.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/supplychain.com/orderers/orderer3.supplychain.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB 
    PreferredMaxBytes: 512 KB
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  FourOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults

      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SupplychainConsortium:
        Organizations:
          - *farmer
          - *warehouse
          - *retailer
          - *transporter
  
  FourOrgsChannel:
    Consortium: SupplychainConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *farmer
        - *warehouse
        - *retailer
        - *transporter
      Capabilities:
        <<: *ApplicationCapabilities