version: '2'

networks: 
  supplychain:

services: 

  ca_farmer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.farmer.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports: 
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/farmer:/etc/hyperledger/fabric-ca-server
    container_name: ca.farmer.supplychain.com
    hostname: ca.farmer.supplychain.com
    networks: 
      - supplychain

  ca_warehouse:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.warehouse.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports: 
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/warehouse:/etc/hyperledger/fabric-ca-server
    container_name: ca.warehouse.supplychain.com
    hostname: ca.warehouse.supplychain.com
    networks: 
      - supplychain

  ca_retailer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.retailer.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports: 
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/retailer:/etc/hyperledger/fabric-ca-server
    container_name: ca.retailer.supplychain.com
    hostname: ca.retailer.supplychain.com
    networks: 
      - supplychain

  ca_transporter:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.transporter.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports: 
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/transporter:/etc/hyperledger/fabric-ca-server
    container_name: ca.transporter.supplychain.com
    hostname: ca.transporter.supplychain.com
    networks: 
      - supplychain

  ca_orderer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports: 
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks: 
      - supplychain